export function toMobileHref(href: string): string {
  if (href === "/m" || href.startsWith("/m/")) return href;
  const mappings: Array<[RegExp, string]> = [
    [/^\/tasks\/([^/?#]+)/, "/m/tasks/$1"],
    [/^\/work-products\/([^/?#]+)/, "/m/work-products/$1"],
    [/^\/documents\/([^/?#]+)/, "/m/documents/$1"],
    [/^\/meeting\/([^/?#]+)/, "/m/meet/$1"],
    [/^\/work-graph/, "/m/work-graph"],
    [/^\/settings/, "/m/settings"],
    [/^\/documents/, "/m/documents"],
    [/^\/tasks/, "/m/tasks"],
    [/^\/work-products/, "/m/work-products"],
    [/^\/projects\/([^/?#]+)/, "/m/projects/$1"],
    [/^\/people\/([^/?#]+)/, "/m/people/$1"],
    [/^\/projects/, "/m/projects"],
    [/^\/calendar/, "/m/calendar"],
    [/^\/people/, "/m/people"],
    [/^\/human-agents/, "/m/human-agents"],
    [/^\/hr/, "/m/hr"],
    [/^\/meetings-manage/, "/m/meetings-manage"],
    [/^\/workflows\/agents/, "/m/workflow-agents"],
    [/^\/workflows/, "/m/workflows"],
    [/^\/knowledge/, "/m/knowledge"],
    [/^\/ai-brain\/skills/, "/m/ai-skills"],
    [/^\/ai-brain/, "/m/ai-brain"],
    [/^\/work-approvals/, "/m/work-approvals"],
    [/^\/decision-history/, "/m/decisions"],
    [/^\/decisions/, "/m/decisions"],
    [/^\/ceo/, "/m/ceo"],
    [/^\/reports/, "/m/reports"],
    [/^\/admin/, "/m/admin"],
    [/^\/billing/, "/m/billing"],
    [/^\/notifications/, "/m/notifications"],
    [/^\/workspace/, "/m/workspace"],
    [/^\/task-ops/, "/m/task-ops"],
    [/^\/work-board/, "/m/work-board"],
    [/^\/work-catalog/, "/m/work-catalog"],
    [/^\/ai-market/, "/m/ai-market"],
    [/^\/ai-workforce/, "/m/ai-workforce"],
    [/^\/email/, "/m/email"],
    [/^\/chat\/([^/?#]+)/, "/m/c/$1"],
    [/^\/chat/, "/m/chat"],
    [/^\/dashboard/, "/m"],
    [/^\/home/, "/m"],
    [/^\/help/, "/m/knowledge"],
  ];
  for (const [pattern, replacement] of mappings) {
    if (pattern.test(href)) return href.replace(pattern, replacement);
  }
  return href.startsWith("/") ? `/m/${href.slice(1)}` : href;
}
