/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MeetingRouteImport } from './routes/meeting'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as WorkflowsRunsRouteImport } from './routes/workflows_.runs'
import { Route as WorkflowsPermissionsRouteImport } from './routes/workflows_.permissions'
import { Route as WorkflowsCalendarRouteImport } from './routes/workflows_.calendar'
import { Route as WorkflowsIdRouteImport } from './routes/workflows.$id'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as ReportsDetailRouteImport } from './routes/reports.detail'
import { Route as ReportsTypeRouteImport } from './routes/reports.$type'
import { Route as MeetingHistoryRouteImport } from './routes/meeting_.history'
import { Route as MeetingIdRouteImport } from './routes/meeting_.$id'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedEmailRouteImport } from './routes/_authenticated/email'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedWorkspaceIndexRouteImport } from './routes/_authenticated/workspace.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as BlogCategoryCategoryRouteImport } from './routes/blog.category.$category'
import { Route as AuthenticatedWorkspaceTagsRouteImport } from './routes/_authenticated/workspace.tags'
import { Route as AuthenticatedWorkspaceSettingsRouteImport } from './routes/_authenticated/workspace.settings'
import { Route as AuthenticatedWorkspaceMembersRouteImport } from './routes/_authenticated/workspace.members'
import { Route as AuthenticatedWorkspaceInviteEmailsRouteImport } from './routes/_authenticated/workspace.invite-emails'
import { Route as AuthenticatedWorkspaceInviteRouteImport } from './routes/_authenticated/workspace.invite'
import { Route as AuthenticatedWorkspaceAuditRouteImport } from './routes/_authenticated/workspace.audit'
import { Route as AuthenticatedWorkspaceIdRouteImport } from './routes/_authenticated/workspace.$id'
import { Route as AuthenticatedPeopleIdRouteImport } from './routes/_authenticated/people_.$id'
import { Route as AuthenticatedNotificationsIdRouteImport } from './routes/_authenticated/notifications.$id'
import { Route as AuthenticatedEmailComposeRouteImport } from './routes/_authenticated/email.compose'
import { Route as AuthenticatedEmailIdRouteImport } from './routes/_authenticated/email.$id'
import { Route as AuthenticatedDocumentsIdRouteImport } from './routes/_authenticated/documents.$id'
import { Route as AuthenticatedChatChannelIdRouteImport } from './routes/_authenticated/chat_.$channelId'
import { Route as AuthenticatedAdminWebhooksRouteImport } from './routes/_authenticated/admin.webhooks'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTraceRouteImport } from './routes/_authenticated/admin.trace'
import { Route as AuthenticatedAdminTenantRouteImport } from './routes/_authenticated/admin.tenant'
import { Route as AuthenticatedAdminRulesRouteImport } from './routes/_authenticated/admin.rules'
import { Route as AuthenticatedAdminQuotaRouteImport } from './routes/_authenticated/admin.quota'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin.plans'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminKnowledgeRouteImport } from './routes/_authenticated/admin.knowledge'
import { Route as ApiPublicHooksProcessQuotaExportsRouteImport } from './routes/api/public/hooks/process-quota-exports'
import { Route as ApiPublicHooksLivekitReconcileRouteImport } from './routes/api/public/hooks/livekit-reconcile'
import { Route as ApiPublicHooksLivekitRouteImport } from './routes/api/public/hooks/livekit'
import { Route as ApiAdminTraceCorrelationIdRouteImport } from './routes/api/admin/trace.$correlationId'
import { Route as AuthenticatedWorkspaceIdStosRouteImport } from './routes/_authenticated/workspace.$id.stos'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRoute = MeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const WorkflowsRunsRoute = WorkflowsRunsRouteImport.update({
  id: '/workflows_/runs',
  path: '/workflows/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsPermissionsRoute = WorkflowsPermissionsRouteImport.update({
  id: '/workflows_/permissions',
  path: '/workflows/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsCalendarRoute = WorkflowsCalendarRouteImport.update({
  id: '/workflows_/calendar',
  path: '/workflows/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIdRoute = WorkflowsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkflowsRoute,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TasksRoute,
} as any)
const ReportsDetailRoute = ReportsDetailRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsTypeRoute = ReportsTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => ReportsRoute,
} as any)
const MeetingHistoryRoute = MeetingHistoryRouteImport.update({
  id: '/meeting_/history',
  path: '/meeting/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingIdRoute = MeetingIdRouteImport.update({
  id: '/meeting_/$id',
  path: '/meeting/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KnowledgeRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailRoute = AuthenticatedEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkspaceIndexRoute =
  AuthenticatedWorkspaceIndexRouteImport.update({
    id: '/workspace/',
    path: '/workspace/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const BlogCategoryCategoryRoute = BlogCategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedWorkspaceTagsRoute =
  AuthenticatedWorkspaceTagsRouteImport.update({
    id: '/workspace/tags',
    path: '/workspace/tags',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceSettingsRoute =
  AuthenticatedWorkspaceSettingsRouteImport.update({
    id: '/workspace/settings',
    path: '/workspace/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceMembersRoute =
  AuthenticatedWorkspaceMembersRouteImport.update({
    id: '/workspace/members',
    path: '/workspace/members',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceInviteEmailsRoute =
  AuthenticatedWorkspaceInviteEmailsRouteImport.update({
    id: '/workspace/invite-emails',
    path: '/workspace/invite-emails',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceInviteRoute =
  AuthenticatedWorkspaceInviteRouteImport.update({
    id: '/workspace/invite',
    path: '/workspace/invite',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceAuditRoute =
  AuthenticatedWorkspaceAuditRouteImport.update({
    id: '/workspace/audit',
    path: '/workspace/audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceIdRoute =
  AuthenticatedWorkspaceIdRouteImport.update({
    id: '/workspace/$id',
    path: '/workspace/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleIdRoute = AuthenticatedPeopleIdRouteImport.update({
  id: '/people_/$id',
  path: '/people/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsIdRoute =
  AuthenticatedNotificationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedNotificationsRoute,
  } as any)
const AuthenticatedEmailComposeRoute =
  AuthenticatedEmailComposeRouteImport.update({
    id: '/compose',
    path: '/compose',
    getParentRoute: () => AuthenticatedEmailRoute,
  } as any)
const AuthenticatedEmailIdRoute = AuthenticatedEmailIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedEmailRoute,
} as any)
const AuthenticatedDocumentsIdRoute =
  AuthenticatedDocumentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)
const AuthenticatedChatChannelIdRoute =
  AuthenticatedChatChannelIdRouteImport.update({
    id: '/chat_/$channelId',
    path: '/chat/$channelId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminWebhooksRoute =
  AuthenticatedAdminWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTraceRoute = AuthenticatedAdminTraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTenantRoute =
  AuthenticatedAdminTenantRouteImport.update({
    id: '/tenant',
    path: '/tenant',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRulesRoute = AuthenticatedAdminRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminQuotaRoute = AuthenticatedAdminQuotaRouteImport.update({
  id: '/quota',
  path: '/quota',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminKnowledgeRoute =
  AuthenticatedAdminKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksProcessQuotaExportsRoute =
  ApiPublicHooksProcessQuotaExportsRouteImport.update({
    id: '/api/public/hooks/process-quota-exports',
    path: '/api/public/hooks/process-quota-exports',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLivekitReconcileRoute =
  ApiPublicHooksLivekitReconcileRouteImport.update({
    id: '/api/public/hooks/livekit-reconcile',
    path: '/api/public/hooks/livekit-reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLivekitRoute = ApiPublicHooksLivekitRouteImport.update({
  id: '/api/public/hooks/livekit',
  path: '/api/public/hooks/livekit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTraceCorrelationIdRoute =
  ApiAdminTraceCorrelationIdRouteImport.update({
    id: '/api/admin/trace/$correlationId',
    path: '/api/admin/trace/$correlationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedWorkspaceIdStosRoute =
  AuthenticatedWorkspaceIdStosRouteImport.update({
    id: '/stos',
    path: '/stos',
    getParentRoute: () => AuthenticatedWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/meeting': typeof MeetingRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/terms': typeof TermsRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/billing': typeof AuthenticatedBillingRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/email': typeof AuthenticatedEmailRouteWithChildren
  '/help': typeof AuthenticatedHelpRoute
  '/notifications': typeof AuthenticatedNotificationsRouteWithChildren
  '/people': typeof AuthenticatedPeopleRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/meeting/$id': typeof MeetingIdRoute
  '/meeting/history': typeof MeetingHistoryRoute
  '/reports/$type': typeof ReportsTypeRoute
  '/reports/detail': typeof ReportsDetailRoute
  '/tasks/$id': typeof TasksIdRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/workflows/calendar': typeof WorkflowsCalendarRoute
  '/workflows/permissions': typeof WorkflowsPermissionsRoute
  '/workflows/runs': typeof WorkflowsRunsRoute
  '/reports/': typeof ReportsIndexRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/quota': typeof AuthenticatedAdminQuotaRoute
  '/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/admin/tenant': typeof AuthenticatedAdminTenantRoute
  '/admin/trace': typeof AuthenticatedAdminTraceRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/chat/$channelId': typeof AuthenticatedChatChannelIdRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/email/$id': typeof AuthenticatedEmailIdRoute
  '/email/compose': typeof AuthenticatedEmailComposeRoute
  '/notifications/$id': typeof AuthenticatedNotificationsIdRoute
  '/people/$id': typeof AuthenticatedPeopleIdRoute
  '/workspace/$id': typeof AuthenticatedWorkspaceIdRouteWithChildren
  '/workspace/audit': typeof AuthenticatedWorkspaceAuditRoute
  '/workspace/invite': typeof AuthenticatedWorkspaceInviteRoute
  '/workspace/invite-emails': typeof AuthenticatedWorkspaceInviteEmailsRoute
  '/workspace/members': typeof AuthenticatedWorkspaceMembersRoute
  '/workspace/settings': typeof AuthenticatedWorkspaceSettingsRoute
  '/workspace/tags': typeof AuthenticatedWorkspaceTagsRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/workspace/$id/stos': typeof AuthenticatedWorkspaceIdStosRoute
  '/api/admin/trace/$correlationId': typeof ApiAdminTraceCorrelationIdRoute
  '/api/public/hooks/livekit': typeof ApiPublicHooksLivekitRoute
  '/api/public/hooks/livekit-reconcile': typeof ApiPublicHooksLivekitReconcileRoute
  '/api/public/hooks/process-quota-exports': typeof ApiPublicHooksProcessQuotaExportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/meeting': typeof MeetingRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/tasks': typeof TasksRouteWithChildren
  '/terms': typeof TermsRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/billing': typeof AuthenticatedBillingRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/email': typeof AuthenticatedEmailRouteWithChildren
  '/help': typeof AuthenticatedHelpRoute
  '/notifications': typeof AuthenticatedNotificationsRouteWithChildren
  '/people': typeof AuthenticatedPeopleRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/meeting/$id': typeof MeetingIdRoute
  '/meeting/history': typeof MeetingHistoryRoute
  '/reports/$type': typeof ReportsTypeRoute
  '/reports/detail': typeof ReportsDetailRoute
  '/tasks/$id': typeof TasksIdRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/workflows/calendar': typeof WorkflowsCalendarRoute
  '/workflows/permissions': typeof WorkflowsPermissionsRoute
  '/workflows/runs': typeof WorkflowsRunsRoute
  '/reports': typeof ReportsIndexRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/quota': typeof AuthenticatedAdminQuotaRoute
  '/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/admin/tenant': typeof AuthenticatedAdminTenantRoute
  '/admin/trace': typeof AuthenticatedAdminTraceRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/chat/$channelId': typeof AuthenticatedChatChannelIdRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/email/$id': typeof AuthenticatedEmailIdRoute
  '/email/compose': typeof AuthenticatedEmailComposeRoute
  '/notifications/$id': typeof AuthenticatedNotificationsIdRoute
  '/people/$id': typeof AuthenticatedPeopleIdRoute
  '/workspace/$id': typeof AuthenticatedWorkspaceIdRouteWithChildren
  '/workspace/audit': typeof AuthenticatedWorkspaceAuditRoute
  '/workspace/invite': typeof AuthenticatedWorkspaceInviteRoute
  '/workspace/invite-emails': typeof AuthenticatedWorkspaceInviteEmailsRoute
  '/workspace/members': typeof AuthenticatedWorkspaceMembersRoute
  '/workspace/settings': typeof AuthenticatedWorkspaceSettingsRoute
  '/workspace/tags': typeof AuthenticatedWorkspaceTagsRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/workspace': typeof AuthenticatedWorkspaceIndexRoute
  '/workspace/$id/stos': typeof AuthenticatedWorkspaceIdStosRoute
  '/api/admin/trace/$correlationId': typeof ApiAdminTraceCorrelationIdRoute
  '/api/public/hooks/livekit': typeof ApiPublicHooksLivekitRoute
  '/api/public/hooks/livekit-reconcile': typeof ApiPublicHooksLivekitReconcileRoute
  '/api/public/hooks/process-quota-exports': typeof ApiPublicHooksProcessQuotaExportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/meeting': typeof MeetingRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/terms': typeof TermsRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/_authenticated/email': typeof AuthenticatedEmailRouteWithChildren
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRouteWithChildren
  '/_authenticated/people': typeof AuthenticatedPeopleRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/meeting_/$id': typeof MeetingIdRoute
  '/meeting_/history': typeof MeetingHistoryRoute
  '/reports/$type': typeof ReportsTypeRoute
  '/reports/detail': typeof ReportsDetailRoute
  '/tasks/$id': typeof TasksIdRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/workflows_/calendar': typeof WorkflowsCalendarRoute
  '/workflows_/permissions': typeof WorkflowsPermissionsRoute
  '/workflows_/runs': typeof WorkflowsRunsRoute
  '/reports/': typeof ReportsIndexRoute
  '/_authenticated/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/quota': typeof AuthenticatedAdminQuotaRoute
  '/_authenticated/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/_authenticated/admin/tenant': typeof AuthenticatedAdminTenantRoute
  '/_authenticated/admin/trace': typeof AuthenticatedAdminTraceRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/_authenticated/chat_/$channelId': typeof AuthenticatedChatChannelIdRoute
  '/_authenticated/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/_authenticated/email/$id': typeof AuthenticatedEmailIdRoute
  '/_authenticated/email/compose': typeof AuthenticatedEmailComposeRoute
  '/_authenticated/notifications/$id': typeof AuthenticatedNotificationsIdRoute
  '/_authenticated/people_/$id': typeof AuthenticatedPeopleIdRoute
  '/_authenticated/workspace/$id': typeof AuthenticatedWorkspaceIdRouteWithChildren
  '/_authenticated/workspace/audit': typeof AuthenticatedWorkspaceAuditRoute
  '/_authenticated/workspace/invite': typeof AuthenticatedWorkspaceInviteRoute
  '/_authenticated/workspace/invite-emails': typeof AuthenticatedWorkspaceInviteEmailsRoute
  '/_authenticated/workspace/members': typeof AuthenticatedWorkspaceMembersRoute
  '/_authenticated/workspace/settings': typeof AuthenticatedWorkspaceSettingsRoute
  '/_authenticated/workspace/tags': typeof AuthenticatedWorkspaceTagsRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/_authenticated/workspace/$id/stos': typeof AuthenticatedWorkspaceIdStosRoute
  '/api/admin/trace/$correlationId': typeof ApiAdminTraceCorrelationIdRoute
  '/api/public/hooks/livekit': typeof ApiPublicHooksLivekitRoute
  '/api/public/hooks/livekit-reconcile': typeof ApiPublicHooksLivekitReconcileRoute
  '/api/public/hooks/process-quota-exports': typeof ApiPublicHooksProcessQuotaExportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/knowledge'
    | '/meeting'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/reports'
    | '/tasks'
    | '/terms'
    | '/workflows'
    | '/admin'
    | '/billing'
    | '/calendar'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/email'
    | '/help'
    | '/notifications'
    | '/people'
    | '/search'
    | '/settings'
    | '/blog/$slug'
    | '/invite/$token'
    | '/knowledge/$slug'
    | '/meeting/$id'
    | '/meeting/history'
    | '/reports/$type'
    | '/reports/detail'
    | '/tasks/$id'
    | '/workflows/$id'
    | '/workflows/calendar'
    | '/workflows/permissions'
    | '/workflows/runs'
    | '/reports/'
    | '/admin/knowledge'
    | '/admin/leads'
    | '/admin/plans'
    | '/admin/quota'
    | '/admin/rules'
    | '/admin/tenant'
    | '/admin/trace'
    | '/admin/users'
    | '/admin/webhooks'
    | '/chat/$channelId'
    | '/documents/$id'
    | '/email/$id'
    | '/email/compose'
    | '/notifications/$id'
    | '/people/$id'
    | '/workspace/$id'
    | '/workspace/audit'
    | '/workspace/invite'
    | '/workspace/invite-emails'
    | '/workspace/members'
    | '/workspace/settings'
    | '/workspace/tags'
    | '/blog/category/$category'
    | '/admin/'
    | '/workspace/'
    | '/workspace/$id/stos'
    | '/api/admin/trace/$correlationId'
    | '/api/public/hooks/livekit'
    | '/api/public/hooks/livekit-reconcile'
    | '/api/public/hooks/process-quota-exports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/knowledge'
    | '/meeting'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/tasks'
    | '/terms'
    | '/workflows'
    | '/billing'
    | '/calendar'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/email'
    | '/help'
    | '/notifications'
    | '/people'
    | '/search'
    | '/settings'
    | '/blog/$slug'
    | '/invite/$token'
    | '/knowledge/$slug'
    | '/meeting/$id'
    | '/meeting/history'
    | '/reports/$type'
    | '/reports/detail'
    | '/tasks/$id'
    | '/workflows/$id'
    | '/workflows/calendar'
    | '/workflows/permissions'
    | '/workflows/runs'
    | '/reports'
    | '/admin/knowledge'
    | '/admin/leads'
    | '/admin/plans'
    | '/admin/quota'
    | '/admin/rules'
    | '/admin/tenant'
    | '/admin/trace'
    | '/admin/users'
    | '/admin/webhooks'
    | '/chat/$channelId'
    | '/documents/$id'
    | '/email/$id'
    | '/email/compose'
    | '/notifications/$id'
    | '/people/$id'
    | '/workspace/$id'
    | '/workspace/audit'
    | '/workspace/invite'
    | '/workspace/invite-emails'
    | '/workspace/members'
    | '/workspace/settings'
    | '/workspace/tags'
    | '/blog/category/$category'
    | '/admin'
    | '/workspace'
    | '/workspace/$id/stos'
    | '/api/admin/trace/$correlationId'
    | '/api/public/hooks/livekit'
    | '/api/public/hooks/livekit-reconcile'
    | '/api/public/hooks/process-quota-exports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/ai'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/knowledge'
    | '/meeting'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/reports'
    | '/tasks'
    | '/terms'
    | '/workflows'
    | '/_authenticated/admin'
    | '/_authenticated/billing'
    | '/_authenticated/calendar'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/email'
    | '/_authenticated/help'
    | '/_authenticated/notifications'
    | '/_authenticated/people'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/blog/$slug'
    | '/invite/$token'
    | '/knowledge/$slug'
    | '/meeting_/$id'
    | '/meeting_/history'
    | '/reports/$type'
    | '/reports/detail'
    | '/tasks/$id'
    | '/workflows/$id'
    | '/workflows_/calendar'
    | '/workflows_/permissions'
    | '/workflows_/runs'
    | '/reports/'
    | '/_authenticated/admin/knowledge'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/quota'
    | '/_authenticated/admin/rules'
    | '/_authenticated/admin/tenant'
    | '/_authenticated/admin/trace'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/webhooks'
    | '/_authenticated/chat_/$channelId'
    | '/_authenticated/documents/$id'
    | '/_authenticated/email/$id'
    | '/_authenticated/email/compose'
    | '/_authenticated/notifications/$id'
    | '/_authenticated/people_/$id'
    | '/_authenticated/workspace/$id'
    | '/_authenticated/workspace/audit'
    | '/_authenticated/workspace/invite'
    | '/_authenticated/workspace/invite-emails'
    | '/_authenticated/workspace/members'
    | '/_authenticated/workspace/settings'
    | '/_authenticated/workspace/tags'
    | '/blog/category/$category'
    | '/_authenticated/admin/'
    | '/_authenticated/workspace/'
    | '/_authenticated/workspace/$id/stos'
    | '/api/admin/trace/$correlationId'
    | '/api/public/hooks/livekit'
    | '/api/public/hooks/livekit-reconcile'
    | '/api/public/hooks/process-quota-exports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  MeetingRoute: typeof MeetingRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  TasksRoute: typeof TasksRouteWithChildren
  TermsRoute: typeof TermsRoute
  WorkflowsRoute: typeof WorkflowsRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  MeetingIdRoute: typeof MeetingIdRoute
  MeetingHistoryRoute: typeof MeetingHistoryRoute
  WorkflowsCalendarRoute: typeof WorkflowsCalendarRoute
  WorkflowsPermissionsRoute: typeof WorkflowsPermissionsRoute
  WorkflowsRunsRoute: typeof WorkflowsRunsRoute
  ApiAdminTraceCorrelationIdRoute: typeof ApiAdminTraceCorrelationIdRoute
  ApiPublicHooksLivekitRoute: typeof ApiPublicHooksLivekitRoute
  ApiPublicHooksLivekitReconcileRoute: typeof ApiPublicHooksLivekitReconcileRoute
  ApiPublicHooksProcessQuotaExportsRoute: typeof ApiPublicHooksProcessQuotaExportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/workflows_/runs': {
      id: '/workflows_/runs'
      path: '/workflows/runs'
      fullPath: '/workflows/runs'
      preLoaderRoute: typeof WorkflowsRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows_/permissions': {
      id: '/workflows_/permissions'
      path: '/workflows/permissions'
      fullPath: '/workflows/permissions'
      preLoaderRoute: typeof WorkflowsPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows_/calendar': {
      id: '/workflows_/calendar'
      path: '/workflows/calendar'
      fullPath: '/workflows/calendar'
      preLoaderRoute: typeof WorkflowsCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$id': {
      id: '/workflows/$id'
      path: '/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof WorkflowsIdRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/reports/detail': {
      id: '/reports/detail'
      path: '/detail'
      fullPath: '/reports/detail'
      preLoaderRoute: typeof ReportsDetailRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/$type': {
      id: '/reports/$type'
      path: '/$type'
      fullPath: '/reports/$type'
      preLoaderRoute: typeof ReportsTypeRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/meeting_/history': {
      id: '/meeting_/history'
      path: '/meeting/history'
      fullPath: '/meeting/history'
      preLoaderRoute: typeof MeetingHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting_/$id': {
      id: '/meeting_/$id'
      path: '/meeting/$id'
      fullPath: '/meeting/$id'
      preLoaderRoute: typeof MeetingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email': {
      id: '/_authenticated/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AuthenticatedEmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/': {
      id: '/_authenticated/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AuthenticatedWorkspaceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/blog/category/$category': {
      id: '/blog/category/$category'
      path: '/category/$category'
      fullPath: '/blog/category/$category'
      preLoaderRoute: typeof BlogCategoryCategoryRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/workspace/tags': {
      id: '/_authenticated/workspace/tags'
      path: '/workspace/tags'
      fullPath: '/workspace/tags'
      preLoaderRoute: typeof AuthenticatedWorkspaceTagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/settings': {
      id: '/_authenticated/workspace/settings'
      path: '/workspace/settings'
      fullPath: '/workspace/settings'
      preLoaderRoute: typeof AuthenticatedWorkspaceSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/members': {
      id: '/_authenticated/workspace/members'
      path: '/workspace/members'
      fullPath: '/workspace/members'
      preLoaderRoute: typeof AuthenticatedWorkspaceMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/invite-emails': {
      id: '/_authenticated/workspace/invite-emails'
      path: '/workspace/invite-emails'
      fullPath: '/workspace/invite-emails'
      preLoaderRoute: typeof AuthenticatedWorkspaceInviteEmailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/invite': {
      id: '/_authenticated/workspace/invite'
      path: '/workspace/invite'
      fullPath: '/workspace/invite'
      preLoaderRoute: typeof AuthenticatedWorkspaceInviteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/audit': {
      id: '/_authenticated/workspace/audit'
      path: '/workspace/audit'
      fullPath: '/workspace/audit'
      preLoaderRoute: typeof AuthenticatedWorkspaceAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/$id': {
      id: '/_authenticated/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof AuthenticatedWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people_/$id': {
      id: '/_authenticated/people_/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof AuthenticatedPeopleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/$id': {
      id: '/_authenticated/notifications/$id'
      path: '/$id'
      fullPath: '/notifications/$id'
      preLoaderRoute: typeof AuthenticatedNotificationsIdRouteImport
      parentRoute: typeof AuthenticatedNotificationsRoute
    }
    '/_authenticated/email/compose': {
      id: '/_authenticated/email/compose'
      path: '/compose'
      fullPath: '/email/compose'
      preLoaderRoute: typeof AuthenticatedEmailComposeRouteImport
      parentRoute: typeof AuthenticatedEmailRoute
    }
    '/_authenticated/email/$id': {
      id: '/_authenticated/email/$id'
      path: '/$id'
      fullPath: '/email/$id'
      preLoaderRoute: typeof AuthenticatedEmailIdRouteImport
      parentRoute: typeof AuthenticatedEmailRoute
    }
    '/_authenticated/documents/$id': {
      id: '/_authenticated/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedDocumentsRoute
    }
    '/_authenticated/chat_/$channelId': {
      id: '/_authenticated/chat_/$channelId'
      path: '/chat/$channelId'
      fullPath: '/chat/$channelId'
      preLoaderRoute: typeof AuthenticatedChatChannelIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/webhooks': {
      id: '/_authenticated/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhooksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/trace': {
      id: '/_authenticated/admin/trace'
      path: '/trace'
      fullPath: '/admin/trace'
      preLoaderRoute: typeof AuthenticatedAdminTraceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tenant': {
      id: '/_authenticated/admin/tenant'
      path: '/tenant'
      fullPath: '/admin/tenant'
      preLoaderRoute: typeof AuthenticatedAdminTenantRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rules': {
      id: '/_authenticated/admin/rules'
      path: '/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AuthenticatedAdminRulesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quota': {
      id: '/_authenticated/admin/quota'
      path: '/quota'
      fullPath: '/admin/quota'
      preLoaderRoute: typeof AuthenticatedAdminQuotaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/knowledge': {
      id: '/_authenticated/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/process-quota-exports': {
      id: '/api/public/hooks/process-quota-exports'
      path: '/api/public/hooks/process-quota-exports'
      fullPath: '/api/public/hooks/process-quota-exports'
      preLoaderRoute: typeof ApiPublicHooksProcessQuotaExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/livekit-reconcile': {
      id: '/api/public/hooks/livekit-reconcile'
      path: '/api/public/hooks/livekit-reconcile'
      fullPath: '/api/public/hooks/livekit-reconcile'
      preLoaderRoute: typeof ApiPublicHooksLivekitReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/livekit': {
      id: '/api/public/hooks/livekit'
      path: '/api/public/hooks/livekit'
      fullPath: '/api/public/hooks/livekit'
      preLoaderRoute: typeof ApiPublicHooksLivekitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/trace/$correlationId': {
      id: '/api/admin/trace/$correlationId'
      path: '/api/admin/trace/$correlationId'
      fullPath: '/api/admin/trace/$correlationId'
      preLoaderRoute: typeof ApiAdminTraceCorrelationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace/$id/stos': {
      id: '/_authenticated/workspace/$id/stos'
      path: '/stos'
      fullPath: '/workspace/$id/stos'
      preLoaderRoute: typeof AuthenticatedWorkspaceIdStosRouteImport
      parentRoute: typeof AuthenticatedWorkspaceIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminKnowledgeRoute: typeof AuthenticatedAdminKnowledgeRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminQuotaRoute: typeof AuthenticatedAdminQuotaRoute
  AuthenticatedAdminRulesRoute: typeof AuthenticatedAdminRulesRoute
  AuthenticatedAdminTenantRoute: typeof AuthenticatedAdminTenantRoute
  AuthenticatedAdminTraceRoute: typeof AuthenticatedAdminTraceRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWebhooksRoute: typeof AuthenticatedAdminWebhooksRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminKnowledgeRoute: AuthenticatedAdminKnowledgeRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedAdminQuotaRoute: AuthenticatedAdminQuotaRoute,
  AuthenticatedAdminRulesRoute: AuthenticatedAdminRulesRoute,
  AuthenticatedAdminTenantRoute: AuthenticatedAdminTenantRoute,
  AuthenticatedAdminTraceRoute: AuthenticatedAdminTraceRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWebhooksRoute: AuthenticatedAdminWebhooksRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDocumentsRouteChildren {
  AuthenticatedDocumentsIdRoute: typeof AuthenticatedDocumentsIdRoute
}

const AuthenticatedDocumentsRouteChildren: AuthenticatedDocumentsRouteChildren =
  {
    AuthenticatedDocumentsIdRoute: AuthenticatedDocumentsIdRoute,
  }

const AuthenticatedDocumentsRouteWithChildren =
  AuthenticatedDocumentsRoute._addFileChildren(
    AuthenticatedDocumentsRouteChildren,
  )

interface AuthenticatedEmailRouteChildren {
  AuthenticatedEmailIdRoute: typeof AuthenticatedEmailIdRoute
  AuthenticatedEmailComposeRoute: typeof AuthenticatedEmailComposeRoute
}

const AuthenticatedEmailRouteChildren: AuthenticatedEmailRouteChildren = {
  AuthenticatedEmailIdRoute: AuthenticatedEmailIdRoute,
  AuthenticatedEmailComposeRoute: AuthenticatedEmailComposeRoute,
}

const AuthenticatedEmailRouteWithChildren =
  AuthenticatedEmailRoute._addFileChildren(AuthenticatedEmailRouteChildren)

interface AuthenticatedNotificationsRouteChildren {
  AuthenticatedNotificationsIdRoute: typeof AuthenticatedNotificationsIdRoute
}

const AuthenticatedNotificationsRouteChildren: AuthenticatedNotificationsRouteChildren =
  {
    AuthenticatedNotificationsIdRoute: AuthenticatedNotificationsIdRoute,
  }

const AuthenticatedNotificationsRouteWithChildren =
  AuthenticatedNotificationsRoute._addFileChildren(
    AuthenticatedNotificationsRouteChildren,
  )

interface AuthenticatedWorkspaceIdRouteChildren {
  AuthenticatedWorkspaceIdStosRoute: typeof AuthenticatedWorkspaceIdStosRoute
}

const AuthenticatedWorkspaceIdRouteChildren: AuthenticatedWorkspaceIdRouteChildren =
  {
    AuthenticatedWorkspaceIdStosRoute: AuthenticatedWorkspaceIdStosRoute,
  }

const AuthenticatedWorkspaceIdRouteWithChildren =
  AuthenticatedWorkspaceIdRoute._addFileChildren(
    AuthenticatedWorkspaceIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRouteWithChildren
  AuthenticatedEmailRoute: typeof AuthenticatedEmailRouteWithChildren
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRouteWithChildren
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedChatChannelIdRoute: typeof AuthenticatedChatChannelIdRoute
  AuthenticatedPeopleIdRoute: typeof AuthenticatedPeopleIdRoute
  AuthenticatedWorkspaceIdRoute: typeof AuthenticatedWorkspaceIdRouteWithChildren
  AuthenticatedWorkspaceAuditRoute: typeof AuthenticatedWorkspaceAuditRoute
  AuthenticatedWorkspaceInviteRoute: typeof AuthenticatedWorkspaceInviteRoute
  AuthenticatedWorkspaceInviteEmailsRoute: typeof AuthenticatedWorkspaceInviteEmailsRoute
  AuthenticatedWorkspaceMembersRoute: typeof AuthenticatedWorkspaceMembersRoute
  AuthenticatedWorkspaceSettingsRoute: typeof AuthenticatedWorkspaceSettingsRoute
  AuthenticatedWorkspaceTagsRoute: typeof AuthenticatedWorkspaceTagsRoute
  AuthenticatedWorkspaceIndexRoute: typeof AuthenticatedWorkspaceIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRouteWithChildren,
  AuthenticatedEmailRoute: AuthenticatedEmailRouteWithChildren,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRouteWithChildren,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedChatChannelIdRoute: AuthenticatedChatChannelIdRoute,
  AuthenticatedPeopleIdRoute: AuthenticatedPeopleIdRoute,
  AuthenticatedWorkspaceIdRoute: AuthenticatedWorkspaceIdRouteWithChildren,
  AuthenticatedWorkspaceAuditRoute: AuthenticatedWorkspaceAuditRoute,
  AuthenticatedWorkspaceInviteRoute: AuthenticatedWorkspaceInviteRoute,
  AuthenticatedWorkspaceInviteEmailsRoute:
    AuthenticatedWorkspaceInviteEmailsRoute,
  AuthenticatedWorkspaceMembersRoute: AuthenticatedWorkspaceMembersRoute,
  AuthenticatedWorkspaceSettingsRoute: AuthenticatedWorkspaceSettingsRoute,
  AuthenticatedWorkspaceTagsRoute: AuthenticatedWorkspaceTagsRoute,
  AuthenticatedWorkspaceIndexRoute: AuthenticatedWorkspaceIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogCategoryCategoryRoute: typeof BlogCategoryCategoryRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogCategoryCategoryRoute: BlogCategoryCategoryRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface KnowledgeRouteChildren {
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeSlugRoute: KnowledgeSlugRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface ReportsRouteChildren {
  ReportsTypeRoute: typeof ReportsTypeRoute
  ReportsDetailRoute: typeof ReportsDetailRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsTypeRoute: ReportsTypeRoute,
  ReportsDetailRoute: ReportsDetailRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface TasksRouteChildren {
  TasksIdRoute: typeof TasksIdRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksIdRoute: TasksIdRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

interface WorkflowsRouteChildren {
  WorkflowsIdRoute: typeof WorkflowsIdRoute
}

const WorkflowsRouteChildren: WorkflowsRouteChildren = {
  WorkflowsIdRoute: WorkflowsIdRoute,
}

const WorkflowsRouteWithChildren = WorkflowsRoute._addFileChildren(
  WorkflowsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  MeetingRoute: MeetingRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReportsRoute: ReportsRouteWithChildren,
  TasksRoute: TasksRouteWithChildren,
  TermsRoute: TermsRoute,
  WorkflowsRoute: WorkflowsRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  MeetingIdRoute: MeetingIdRoute,
  MeetingHistoryRoute: MeetingHistoryRoute,
  WorkflowsCalendarRoute: WorkflowsCalendarRoute,
  WorkflowsPermissionsRoute: WorkflowsPermissionsRoute,
  WorkflowsRunsRoute: WorkflowsRunsRoute,
  ApiAdminTraceCorrelationIdRoute: ApiAdminTraceCorrelationIdRoute,
  ApiPublicHooksLivekitRoute: ApiPublicHooksLivekitRoute,
  ApiPublicHooksLivekitReconcileRoute: ApiPublicHooksLivekitReconcileRoute,
  ApiPublicHooksProcessQuotaExportsRoute:
    ApiPublicHooksProcessQuotaExportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
