/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as MeetingRouteImport } from './routes/meeting'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as WorkflowsIdRouteImport } from './routes/workflows.$id'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as ReportsTypeRouteImport } from './routes/reports.$type'
import { Route as PeopleIdRouteImport } from './routes/people.$id'
import { Route as MeetingIdRouteImport } from './routes/meeting.$id'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge.$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedEmailRouteImport } from './routes/_authenticated/email'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedWorkspaceIdRouteImport } from './routes/_authenticated/workspace.$id'
import { Route as AuthenticatedDocumentsIdRouteImport } from './routes/_authenticated/documents.$id'
import { Route as AuthenticatedWorkspaceIdStosRouteImport } from './routes/_authenticated/workspace.$id.stos'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRoute = MeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const WorkflowsIdRoute = WorkflowsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkflowsRoute,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TasksRoute,
} as any)
const ReportsTypeRoute = ReportsTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => ReportsRoute,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PeopleRoute,
} as any)
const MeetingIdRoute = MeetingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MeetingRoute,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KnowledgeRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailRoute = AuthenticatedEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkspaceIdRoute =
  AuthenticatedWorkspaceIdRouteImport.update({
    id: '/workspace/$id',
    path: '/workspace/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsIdRoute =
  AuthenticatedDocumentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)
const AuthenticatedWorkspaceIdStosRoute =
  AuthenticatedWorkspaceIdStosRouteImport.update({
    id: '/stos',
    path: '/stos',
    getParentRoute: () => AuthenticatedWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/meeting': typeof MeetingRouteWithChildren
  '/people': typeof PeopleRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/workflows': typeof WorkflowsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/email': typeof AuthenticatedEmailRoute
  '/help': typeof AuthenticatedHelpRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/meeting/$id': typeof MeetingIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/reports/$type': typeof ReportsTypeRoute
  '/tasks/$id': typeof TasksIdRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/reports/': typeof ReportsIndexRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/workspace/$id': typeof AuthenticatedWorkspaceIdRouteWithChildren
  '/workspace/$id/stos': typeof AuthenticatedWorkspaceIdStosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/meeting': typeof MeetingRouteWithChildren
  '/people': typeof PeopleRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/workflows': typeof WorkflowsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/email': typeof AuthenticatedEmailRoute
  '/help': typeof AuthenticatedHelpRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/meeting/$id': typeof MeetingIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/reports/$type': typeof ReportsTypeRoute
  '/tasks/$id': typeof TasksIdRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/reports': typeof ReportsIndexRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/workspace/$id': typeof AuthenticatedWorkspaceIdRouteWithChildren
  '/workspace/$id/stos': typeof AuthenticatedWorkspaceIdStosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/meeting': typeof MeetingRouteWithChildren
  '/people': typeof PeopleRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/workflows': typeof WorkflowsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/_authenticated/email': typeof AuthenticatedEmailRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/meeting/$id': typeof MeetingIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/reports/$type': typeof ReportsTypeRoute
  '/tasks/$id': typeof TasksIdRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/reports/': typeof ReportsIndexRoute
  '/_authenticated/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/_authenticated/workspace/$id': typeof AuthenticatedWorkspaceIdRouteWithChildren
  '/_authenticated/workspace/$id/stos': typeof AuthenticatedWorkspaceIdStosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/auth'
    | '/chat'
    | '/knowledge'
    | '/meeting'
    | '/people'
    | '/reports'
    | '/tasks'
    | '/workflows'
    | '/dashboard'
    | '/documents'
    | '/email'
    | '/help'
    | '/notifications'
    | '/settings'
    | '/knowledge/$slug'
    | '/meeting/$id'
    | '/people/$id'
    | '/reports/$type'
    | '/tasks/$id'
    | '/workflows/$id'
    | '/reports/'
    | '/documents/$id'
    | '/workspace/$id'
    | '/workspace/$id/stos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/auth'
    | '/chat'
    | '/knowledge'
    | '/meeting'
    | '/people'
    | '/tasks'
    | '/workflows'
    | '/dashboard'
    | '/documents'
    | '/email'
    | '/help'
    | '/notifications'
    | '/settings'
    | '/knowledge/$slug'
    | '/meeting/$id'
    | '/people/$id'
    | '/reports/$type'
    | '/tasks/$id'
    | '/workflows/$id'
    | '/reports'
    | '/documents/$id'
    | '/workspace/$id'
    | '/workspace/$id/stos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai'
    | '/auth'
    | '/chat'
    | '/knowledge'
    | '/meeting'
    | '/people'
    | '/reports'
    | '/tasks'
    | '/workflows'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/email'
    | '/_authenticated/help'
    | '/_authenticated/notifications'
    | '/_authenticated/settings'
    | '/knowledge/$slug'
    | '/meeting/$id'
    | '/people/$id'
    | '/reports/$type'
    | '/tasks/$id'
    | '/workflows/$id'
    | '/reports/'
    | '/_authenticated/documents/$id'
    | '/_authenticated/workspace/$id'
    | '/_authenticated/workspace/$id/stos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  MeetingRoute: typeof MeetingRouteWithChildren
  PeopleRoute: typeof PeopleRouteWithChildren
  ReportsRoute: typeof ReportsRouteWithChildren
  TasksRoute: typeof TasksRouteWithChildren
  WorkflowsRoute: typeof WorkflowsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/workflows/$id': {
      id: '/workflows/$id'
      path: '/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof WorkflowsIdRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/reports/$type': {
      id: '/reports/$type'
      path: '/$type'
      fullPath: '/reports/$type'
      preLoaderRoute: typeof ReportsTypeRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/meeting/$id': {
      id: '/meeting/$id'
      path: '/$id'
      fullPath: '/meeting/$id'
      preLoaderRoute: typeof MeetingIdRouteImport
      parentRoute: typeof MeetingRoute
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email': {
      id: '/_authenticated/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AuthenticatedEmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/$id': {
      id: '/_authenticated/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof AuthenticatedWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/$id': {
      id: '/_authenticated/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedDocumentsRoute
    }
    '/_authenticated/workspace/$id/stos': {
      id: '/_authenticated/workspace/$id/stos'
      path: '/stos'
      fullPath: '/workspace/$id/stos'
      preLoaderRoute: typeof AuthenticatedWorkspaceIdStosRouteImport
      parentRoute: typeof AuthenticatedWorkspaceIdRoute
    }
  }
}

interface AuthenticatedDocumentsRouteChildren {
  AuthenticatedDocumentsIdRoute: typeof AuthenticatedDocumentsIdRoute
}

const AuthenticatedDocumentsRouteChildren: AuthenticatedDocumentsRouteChildren =
  {
    AuthenticatedDocumentsIdRoute: AuthenticatedDocumentsIdRoute,
  }

const AuthenticatedDocumentsRouteWithChildren =
  AuthenticatedDocumentsRoute._addFileChildren(
    AuthenticatedDocumentsRouteChildren,
  )

interface AuthenticatedWorkspaceIdRouteChildren {
  AuthenticatedWorkspaceIdStosRoute: typeof AuthenticatedWorkspaceIdStosRoute
}

const AuthenticatedWorkspaceIdRouteChildren: AuthenticatedWorkspaceIdRouteChildren =
  {
    AuthenticatedWorkspaceIdStosRoute: AuthenticatedWorkspaceIdStosRoute,
  }

const AuthenticatedWorkspaceIdRouteWithChildren =
  AuthenticatedWorkspaceIdRoute._addFileChildren(
    AuthenticatedWorkspaceIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRouteWithChildren
  AuthenticatedEmailRoute: typeof AuthenticatedEmailRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWorkspaceIdRoute: typeof AuthenticatedWorkspaceIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRouteWithChildren,
  AuthenticatedEmailRoute: AuthenticatedEmailRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWorkspaceIdRoute: AuthenticatedWorkspaceIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface KnowledgeRouteChildren {
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeSlugRoute: KnowledgeSlugRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface MeetingRouteChildren {
  MeetingIdRoute: typeof MeetingIdRoute
}

const MeetingRouteChildren: MeetingRouteChildren = {
  MeetingIdRoute: MeetingIdRoute,
}

const MeetingRouteWithChildren =
  MeetingRoute._addFileChildren(MeetingRouteChildren)

interface PeopleRouteChildren {
  PeopleIdRoute: typeof PeopleIdRoute
}

const PeopleRouteChildren: PeopleRouteChildren = {
  PeopleIdRoute: PeopleIdRoute,
}

const PeopleRouteWithChildren =
  PeopleRoute._addFileChildren(PeopleRouteChildren)

interface ReportsRouteChildren {
  ReportsTypeRoute: typeof ReportsTypeRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsTypeRoute: ReportsTypeRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface TasksRouteChildren {
  TasksIdRoute: typeof TasksIdRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksIdRoute: TasksIdRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

interface WorkflowsRouteChildren {
  WorkflowsIdRoute: typeof WorkflowsIdRoute
}

const WorkflowsRouteChildren: WorkflowsRouteChildren = {
  WorkflowsIdRoute: WorkflowsIdRoute,
}

const WorkflowsRouteWithChildren = WorkflowsRoute._addFileChildren(
  WorkflowsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  MeetingRoute: MeetingRouteWithChildren,
  PeopleRoute: PeopleRouteWithChildren,
  ReportsRoute: ReportsRouteWithChildren,
  TasksRoute: TasksRouteWithChildren,
  WorkflowsRoute: WorkflowsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
