/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeetingRouteImport } from './routes/meeting'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'

const MeetingRoute = MeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/knowledge': typeof KnowledgeRoute
  '/meeting': typeof MeetingRoute
  '/documents': typeof AuthenticatedDocumentsRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/knowledge': typeof KnowledgeRoute
  '/meeting': typeof MeetingRoute
  '/documents': typeof AuthenticatedDocumentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/knowledge': typeof KnowledgeRoute
  '/meeting': typeof MeetingRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/knowledge' | '/meeting' | '/documents'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/knowledge' | '/meeting' | '/documents'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/knowledge'
    | '/meeting'
    | '/_authenticated/documents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KnowledgeRoute: typeof KnowledgeRoute
  MeetingRoute: typeof MeetingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KnowledgeRoute: KnowledgeRoute,
  MeetingRoute: MeetingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
